services:
  keycloak:
    container_name: key_cloak-container
    image: quay.io/keycloak/keycloak:26.0.1
    ports:
      - "8080:8080"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    command: start-dev
